services:
  db:
    image: postgres:17-alpine
    env_file:
      - config.env
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: unless-stopped
  app:
    build: .
    env_file:
      - config.env
    ports:
      - "8090:8090"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pg-data:
