// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/google/uuid"
)

type Wallet struct {
	ID      uuid.UUID `json:"id"`
	Balance int32     `json:"balance"`
}
