// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: wallet.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getWalletByID = `-- name: GetWalletByID :one
SELECT id, balance FROM wallets WHERE id = $1
`

func (q *Queries) GetWalletByID(ctx context.Context, id uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByID, id)
	var i Wallet
	err := row.Scan(&i.ID, &i.Balance)
	return i, err
}

const updateWallet = `-- name: UpdateWallet :one
UPDATE wallets 
SET balance = balance + $1
WHERE id = $2
RETURNING id, balance
`

type UpdateWalletParams struct {
	Amount int32     `json:"amount"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateWallet(ctx context.Context, arg UpdateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, updateWallet, arg.Amount, arg.ID)
	var i Wallet
	err := row.Scan(&i.ID, &i.Balance)
	return i, err
}
